### ISSUE TITLE
Seems to fail on Windows / AppVeyor

### ISSUE THREAD

**Issue by swernerx** [ai/size-limit#12]
I have installed size-limit in one of my packages to watch the sizes during CI testing which is pretty useful. Unfortunately just calling size-limit on AppVeyor - the typical Windows CI - crashes. Unfortunately not a lot of details are shown.

Log is available here: 
https://ci.appveyor.com/project/swernerx/edge-core/build/109/job/ulwvqk1xdwfr5y0x

I figure it would be useful to add CI testing with AppVeyor to Size-Limit as well. Hopefully someone has an idea of the reasons behind the failure.

**Comment by swernerx** [comment]
What actually confuses me is that it worked in the last iteration. Maybe it's an appveyor specific issue.

See the log:

**Comment by ai** [comment]
I think we should run Size Limit tests on AppVeyor too. Wait for a second, I create the project there.

**Comment by ai** [comment]
Are you sure, that it is not from `prepublish` command?

**Comment by ai** [comment]
Sad news, Size Limit works good on AppVeyor https://ci.appveyor.com/project/ai/size-limit

**Comment by ai** [comment]
I released 0.8.3 with better error messages. Could you test again with it?

**Comment by swernerx** [comment]
Still seems to be broken for me. Node v6 only BTW: https://travis-ci.org/sebastian-software/edge-core/jobs/263067471

**Comment by swernerx** [comment]
That's probably a difference :) You are currently only testing on v8.

**Comment by ai** [comment]
Still good on Node.js 6 too https://ci.appveyor.com/project/ai/size-limit

**Comment by ai** [comment]
BTW, I think I found what it is the problem. It is not related with Windows.

When somebody will build your project with Webpack, it will not have `fs` because of `fs` available only in Node.js, not in the browser. So you must add this lines to your `package.json`:

https://github.com/postcss/postcss/blob/45cf0a172b6720505be9da0dde78a54138e2cc13/package.json#L71-L73

**Comment by swernerx** [comment]
Thanks for the hint with the "browser" config. Actually it should never hit this as there are two different output scenarios for the library "web" and "node". These are the entries in the `package.json`:

```json
  "main": "lib/node.es5.cjs.js",
  "module": "lib/node.es5.esm.js",
  "browser": "lib/browser.es5.esm.js",
```

Which entry is `size-limit` using? Because the "browser" entry point is not accessing any `fs` at all.

**Comment by ai** [comment]
Size Limit take file from `size-limit` section and pack it with webpack. As result because of this section:

```
    {
      "path": "lib/node.es5.esm.js",
      "limit": "1000 KB"
    }
```

It will take `lib/node.es5.esm.js` and will try to pack it in webpack and will have issue (because packing is impossible).

In your case there is no big sense to test `lib/node.es5.esm.js` size, since it doesn’t go to browser and size is not critical.

**Comment by swernerx** [comment]
That's the issue. You are absolutely right. Thanks!
