### ISSUE TITLE
Support page chunks

### ISSUE THREAD

**Issue by mxstbr** [ai/size-limit#125]
When building an app with create-react-app (or Next.js or most other React frameworks) you usually end up with many individual bundle chunks. 

Almost always, only a small number of them will be loaded at a time to ensure that each page loads as quickly as possible and only includes the code it needs.

Right now with size-limit I can only check how big my app would be if I loaded _all_ chunks at once, but that would never happen (that's why I have multiple chunks in the first place 😅). Is there a way to make it so that it checks the size of each chunk + the main chunk (which is always loaded) individually or something like that?

**Comment by ai** [comment]
In our app I use named chunks and this config:

```
[
  {
     name: "critical",
     path: ["dist/app-*.is", "dist/app-*.css"]
  },
  {
    name: "important pages",
    path: ["dist/often-*.is", "dist/often-*.css"]
  }
]
```

Will it works for you?

**Comment by mxstbr** [comment]
That makes sense, yes. Can I set up a "default" for all other chunks, or will this run the `main.js` file twice?

```JS
[{
  name: "main bundle",
  path: "dist/main.*.js"
}, {
  name: "others",
  path: "dist/*.js"
}]
```

**Comment by ai** [comment]
`["dist/*.js", "!dist/main.*.js"]`

How we can make these features more discoverable in the docs?

**Comment by rtymchyk** [comment]
@ai Is there a way to set up a default for all other chunks, that sets a limit per chunk?

For example, in our webpack app, we code split by page, so we end up with a bunch of `public/dist/components-pages*.js` files that webpack splits out.

I'd like to set a maximum size limit that's per file, not per that full group of files. But at the same time I don't want to manually add a new entry for each page, because there are dozens of them and growing.

**Comment by ai** [comment]
It is not the goal of this project. We try to limit the total price of app (or some feature), not per-chunk parameters.

I think webpack has build-in chunk size warning.

**Comment by rtymchyk** [comment]
Ok, thanks for the reply.
