### ISSUE TITLE
Work with Raisl 5 + Webpacker?

### ISSUE THREAD

**Issue by bilbosan** [ai/size-limit#27]
It seems to work with Webpacker, but the `--why` doesn't spit anything out.

In package.json:

```
  "scripts": {
    "size": "size-limit"
  },
  "size-limit": [
    {
      "path": "./app/javascript/packs/player.js"
    }
  ],

```

When I run it:

```
→ NODE_ENV=test npm run size --why

> @ size /Users/patrick.minton/src/boxscoregeeks
> size-limit


  Package size: 134 B
  With all dependencies, minified and gzipped


```

(but no browser window opens). I tried with and without `NODE_ENV=test` (hoping that with test, it would spit out a static HTML file).

this is on a Mac running Sierra, in a Rails 5.1 project that uses webpacker

Any thoughts?

**Comment by ai** [comment]
Right now `--why` doesn’t work when you have own builder. Because Webpack Bundle Analyzer must be inserted in the builder.

I am not sure is it possible to set Webpack Bundle Analyzer plugin to Webpacker.

I have some ideas how we can use `--why` with a custom builder, but I will think about this issue only after my talk about Logux on ReactiveConf.

**Comment by ai** [comment]
> but no browser window opens

This happens because when you write `npm run size --why`, `--why` does to `npm`, not to `size-limit`. In your case you need to call `npx size-limit --why`.

**Comment by ai** [comment]
Seems like this docs could help you with inserting [Webpack Bundle Analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) plugin to Webpacker: https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins
