### ISSUE TITLE
Error: “Size Limit can't resolve fs”

### ISSUE THREAD

**Issue by jaydenseric** [ai/size-limit#65]
When attempting to run size-limit, I get this error:

```
 ERROR  Size Limit can't resolve
        fs
        in /Users/jaydenseric/Sites/apollo-upload-server/node_modules/busboy/lib
```

When using `"webpack": false` the error does not appear.

**Comment by ai** [comment]
Hi. This error happens because Size Limit try to make browser version of your project (packing it by webpack) and there will not be `fs` module in browser.

There is a multiple ways to solve the problem. I need to know more before give you AP advise.

Do you run Size Limit on server-side project? Why do you care about size of server size project?

**Comment by jaydenseric** [comment]
> Do you run Size Limit on server-side project?

Yes.

>Why do you care about size of server size project?

Because I am a responsible package author, and want to ensure my packages are lean and efficient. This is particularly important for consumers that use Webpack or Babel to process their server-side code; they don't want huge bundles or compile times.

**Comment by ai** [comment]
Interesting use case. So you want to use Size Limit to control how much file size your project will have in user's `node_modules`?

**Comment by jaydenseric** [comment]
Yep! While being aware of the size of my package code is interesting, it is also interesting to check my dependencies are not a horrific burden for consumer’s `node_modules`.

**Comment by ai** [comment]
I have two news:

1. Size Limit was not designed for this use cases.
2. But I really like your idea. I will try to implement it. Unfortunately, it could take few weeks. I will add special option to ignore all Node.js modules and disable gzip and uglify.

Here is a temporary workaround:

1. Add `browser: { fs: false }` to your `package.json`. It will say for webpack to ignore this module.
2. Add `gzip: false` to Size Limit config since you are care about size on the disk.

Will like work for you until I will finding better solution?

**Comment by Siilwyn** [comment]
Another use-case is for CLI packages, I'm currently searching for a way to keep the size in check. I found the module [cost-of-modules](https://github.com/siddharthkp/cost-of-modules) which does the job put returns the size of all modules instead of only the total size. I've opened an issue about it: https://github.com/siddharthkp/cost-of-modules/issues/51

**Comment by ai** [comment]
@Siilwyn :+1:

**Comment by styfle** [comment]
If I could jump in here, I might have some relevant info...

I have done a lot of research in this area and listed many similar tools here: https://github.com/styfle/packagephobia#how-is-this-different

I wrote Package Phobia to find the npm install size of package and protect against dependency. You can even add badge to your README to keep the size in check.

I hope that helps 😄

**Comment by ai** [comment]
@styfle I very like the project. It will be more accurate than Size Limit since it will calculate also non-jS files. Do you have CI tool to run it in Travis CI?

**Comment by styfle** [comment]
@ai Thanks for the kind words 😄 

You are correct that Package Phobia will calculate non-JS files too (its looks at everything published to npm including the README.md file).

I do not currently have a CI tool because of the architecture...

Package Phobia is actually downloading the data *after* it's been published to npm--a CI tool would probably want to run *before* you publish to npm.

In that case, it's probably more appropriate to add this type of feature in one of these existing CLI tools:

- [Cost Of Modules](https://github.com/siddharthkp/cost-of-modules)
- [Bundle Size](https://github.com/siddharthkp/bundlesize)
- [Package Size](https://github.com/egoist/package-size)
- [Size Limit](https://github.com/ai/size-limit) (this one 😸)

**Comment by Siilwyn** [comment]
@styfle very nice service indeed! Sadly as you already mentioned it checks the size after it is published while I would like to check the size in PRs.

Regarding the CLI tools:
*   [Cost Of Modules](https://github.com/siddharthkp/cost-of-modules): [rejected](https://github.com/siddharthkp/cost-of-modules/issues/51#issuecomment-395681400)
*   [Bundle Size](https://github.com/siddharthkp/bundlesize): does not include the total size, assumes a build 'dist.js'
*   [Package Size](https://github.com/egoist/package-size): bundles with webpack
*   [Size Limit](https://github.com/ai/size-limit): well... here we are :D

**Comment by styfle** [comment]
Package Size does have an issue open for this so I think the author might be interested: https://github.com/egoist/package-size/issues/16

**Comment by styfle** [comment]
Also note that npm actually has the concept of a publish "dry run".

They call it `npm pack`.

> For a "dry run" that does everything except actually publishing to the registry, see [npm-pack](https://docs.npmjs.com/cli/pack), which figures out the files to be included and packs them into a tarball to be uploaded to the registry.

Now this size is compress so it will be smaller than what Package Phobia reports (which is the uncompressed size) but I think the [comment here](https://github.com/siddharthkp/cost-of-modules/issues/51#issuecomment-395681400) explains pretty well how to find the uncompressed size.

**Comment by Siilwyn** [comment]
`npm pack` does not include the `node_modules` and yeah I've seen that comment since I created that issue. :D
Maybe I should create a package for it to re-use it in other projects. It's not perfect though since this will include development dependencies too, unless you would ofc. remove the node modules and only install the normal dependencies beforehand on the CI.

**Comment by ai** [comment]
We can do:

1. npm pack
2. unzip package to temporary dir
3. npm install
4. Check dir size

But we must to do it in separated project. Maybe `package-limit`?

**Comment by jonathantneal** [comment]
I am having a similar issue with the same error message. I have only 2 files, `index.js` and `package.json`:

```js
module.exports = require('mdn-browser-compat-data');
```

```json
{
  "scripts": {
    "test": "size-limit"
  },
  "devDependencies": {
    "mdn-browser-compat-data": "0.0.85",
    "size-limit": "^1.3.7"
  },
  "browser": {
    "fs": false
  },
  "size-limit": [
    {
      "path": "index.js"
    }
  ],
  "private": true
}
```

Running `npm test` produces the following error:

```
 ERROR  Size Limit can't resolve
        fs
        in /test/node_modules/mdn-browser-compat-data
```

It may be important to note that `mdn-browser-compat-data` is a JS file which uses `fs` to load all of its data (see https://unpkg.com/mdn-browser-compat-data@0.0.85/index.js).

However, this fools tools like **BundlePhobia** into believing the library is only **975** bytes, minified and gzipped (see https://bundlephobia.com/result?p=mdn-browser-compat-data@0.0.85).

---

Right now, my workaround is to write the export of **mdn-browser-compat-data** to a new JSON file and to run **size-limit** against that:

```js
require('fs').writeFileSync(
  'index.json',
  JSON.stringify(
    require('mdn-browser-compat-data')
  )
);
```

```diff
  "size-limit": [
    {
-      "path": "index.js"
+      "path": "index.json"
```

Then, running **npm test** produces the following result:

```
  Package size: 363.96 KB with all dependencies, minified and gzipped
  Loading time: 7.3 s     on slow 3G
  Running time: 7.7 s     on Snapdragon 410
  Total time:   15 s
```

And I would say **363.96** kilobytes is not quite the same as **375** bytes. 😄

**Comment by ai** [comment]
1. Can you try to add `ignore: ['fs']` to Size Limit config
2. 975 bytes is a strange number for `

**Comment by jonathantneal** [comment]
1. Yes, adding the `ignore` config resolves the error.

```json
{
  "scripts": {
    "test": "size-limit"
  },
  "devDependencies": {
    "mdn-browser-compat-data": "0.0.85",
    "size-limit": "^1.3.7"
  },
  "browser": {
    "fs": false
  },
  "size-limit": [
    {
      "path": "index.js",
      "ignore": [
        "fs"
      ]
    }
  ],
  "private": true
}
```

After making this change, running **npm test** produces the following result:

```
  Package size: 2.21 KB with all dependencies, minified and gzipped
  Loading time: 45 ms   on slow 3G
  Running time: 101 ms  on Snapdragon 410
  Total time:   145 ms
```

2a. Yes, 975 bytes is a strange number for a library with data, especially when `size-limit` ignored these statements and still reported **2.21** kilobytes.

2b. My tool is not necessarily intended for the browser. Instead, like **caniuse-lite**, it is intended for other tooling, which could be used in a browser. For now, I am mostly interested in producing a smaller version of **mdn-browser-compat-data** that uses **browserslist** compatible browser names to reduce the overhead required to use this data with other tooling, namely PostCSS.

2c. In **mdn-browser-compat-data**, the data is loaded with `fs`. I’m not sure how it will work for my tooling yet.

**Comment by ai** [comment]
1. I will think about adding `fs` as default ignore.
2. You can use `--output-bundle` to get output JS and see what webpack put there

**Comment by ai** [comment]
I decided that at least for now, `fs` will not be part as default. It is much safer to explicitly define it in `ignore` or in `browsers`.

If we will have this issue again in the future, I can change my mind.
